// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindTraderieItem(arg1) {
  return window['go']['main']['App']['FindTraderieItem'](arg1);
}

export function GenerateSearchURL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateSearchURL'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllItems() {
  return window['go']['main']['App']['GetAllItems']();
}

export function GetAuthToken() {
  return window['go']['main']['App']['GetAuthToken']();
}

export function GetCookieSetupInstructions() {
  return window['go']['main']['App']['GetCookieSetupInstructions']();
}

export function GetPropertyMapping(arg1) {
  return window['go']['main']['App']['GetPropertyMapping'](arg1);
}

export function GetTradingOptions() {
  return window['go']['main']['App']['GetTradingOptions']();
}

export function HasSavedCookies() {
  return window['go']['main']['App']['HasSavedCookies']();
}

export function OpenURLInExtension(arg1) {
  return window['go']['main']['App']['OpenURLInExtension'](arg1);
}

export function PostItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PostItem'](arg1, arg2, arg3, arg4);
}

export function RefreshListings() {
  return window['go']['main']['App']['RefreshListings']();
}

export function SavePropertyMappings(arg1) {
  return window['go']['main']['App']['SavePropertyMappings'](arg1);
}

export function SaveTradingOptions(arg1) {
  return window['go']['main']['App']['SaveTradingOptions'](arg1);
}

export function SetAuthToken(arg1) {
  return window['go']['main']['App']['SetAuthToken'](arg1);
}

export function SetupCookies(arg1) {
  return window['go']['main']['App']['SetupCookies'](arg1);
}

export function StartAutoRefresh() {
  return window['go']['main']['App']['StartAutoRefresh']();
}

export function StopAutoRefresh() {
  return window['go']['main']['App']['StopAutoRefresh']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
