// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {traderie} from '../models';

export function FindTraderieItem(arg1:models.Item):Promise<traderie.TraderieItem|boolean>;

export function GenerateSearchURL(arg1:models.Item,arg2:number,arg3:Array<Record<string, string>>,arg4:Array<string>,arg5:Record<string, any>):Promise<string>;

export function GetAllItems():Promise<Array<string>>;

export function GetAttachedProcesses():Promise<Array<Record<string, any>>>;

export function GetAuthToken():Promise<string>;

export function GetCookieSetupInstructions():Promise<string>;

export function GetPropertyMapping(arg1:string):Promise<string>;

export function GetTradingOptions():Promise<Record<string, any>>;

export function HasSavedCookies():Promise<boolean>;

export function OpenURLInExtension(arg1:string):Promise<void>;

export function PostItem(arg1:models.Item,arg2:string,arg3:Record<string, any>,arg4:Record<string, any>):Promise<void>;

export function RefreshD2RProcesses():Promise<void>;

export function RefreshListings():Promise<void>;

export function SavePropertyMappings(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveTradingOptions(arg1:Record<string, any>):Promise<void>;

export function SetAuthToken(arg1:string):Promise<void>;

export function SetupCookies(arg1:string):Promise<void>;

export function StartAutoRefresh():Promise<void>;

export function StopAutoRefresh():Promise<void>;

export function TestConnection():Promise<void>;
